### ISSUE TITLE
Support private npm packages

### ISSUE THREAD

**Issue by timiyay** [simplabs/ember-asset-size-action#17]
I trialled this Github Action, but am unable to pass the `yarn install` stage since we can't access our private npm packages.

Does this action support any way of passing this token, or, is there a complimentary Github Action that can be used to make this available?

**Comment by mydea** [comment]
We have made it work by adding this step before:

```yml
- name: Setup Github Package Repository access token
  run: echo ${{ secrets.GITHUB_NPM_TOKEN_FULL }} > ~/.npmrc
```

And add a secret `GITHUB_NPM_TOKEN_FULL` that looks like this: 

```
//npm.pkg.github.com/:_authToken=MY_TOKEN
```

The same would work, I presume, with a private npm registry.

**Comment by timiyay** [comment]
Thanks for the suggestion @mydea. That works out for us.

I should've done some more research to understand how Github Action steps can be composed. They're somewhat new to me, and the other JS actions I'd used would take `NPM_TOKEN` in `env`, so I was wondering if this action did too.

I'll close this, since it can be solved without adding code to this repo.
