### ISSUE TITLE
Edit comment if it exists?

### ISSUE THREAD

**Issue by backspace** [simplabs/ember-asset-size-action#9]
Hey, we’re considering using this for [the HashiCorp Nomad UI](https://github.com/hashicorp/nomad/tree/master/ui) so we can track the effects of updates and jQuery-removal etc, hence my experimentation with #6. From past experience, I’ve become annoyed by things that post a comment for every push because I am of the push-early-push-often style and it adds a lot of noise.

Would you be interested if I made a PR that added the option to have the comment be updated (replaced) if it already exists? Somewhat akin to what [Codecov does](https://docs.codecov.io/docs/pull-request-comments#behavior), though I think `new` and `update` are the only options necessary.

**Comment by backspace** [comment]
I did some preliminary work on this, you can see [here](https://github.com/backspace/ember-asset-size-action/compare/working-directory-fixes...backspace:edit-comment) that the diff isn’t too significant, though it doesn’t involve any configurability.

**Comment by Techn1x** [comment]
I could really use this too

**Comment by Techn1x** [comment]
Added PR to implement the feature
https://github.com/simplabs/ember-asset-size-action/pull/18

**Comment by rahulk94** [comment]
We've recently started looking at using this action and re-using the same comment would be really beneficial for us. I can help get this over the line
